### ISSUE TITLE
olap4j-xmlaserver don't include the license file

### ISSUE THREAD

**Issue by puntogil** [olap4j/olap4j-xmlaserver#18]
Hi
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
Thanks in advance
Regards

**Comment by julianhyde** [comment]
Fixed in 7e4dd00b38cc28d94fe7ba4a79abef393d147977 on master branch, 559b2ee2733018e509ad5c00bbe4d9e0c97f1458 on olap4j2 branch.

**Comment by puntogil** [comment]
Sorry for the question, pom.xml file and 
/src/main/java/org/olap4j/xmla/server/impl/StringEscaper.java
are license under Apache 2 license, is intentional? or the license project is EPLv1.0?
